# Generated by Django 5.0 on 2023-12-19 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_delete_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, default='static/post_default.png', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='texto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
